@startuml rete
garg2e2_ -> nnn2_ 
farg2e2_ -> nnn2_
echo_deb_ -> nnn2_
nnn2_ -> nnn2_:is_num
nnn2_ -> nnn2_:exit_err_nnn2_
nnn2_ -> nnn2_:exit_reg_nnn2_
nnn2_ -> nnn2_:unset_autoargs_nnn2_
' {wrap_fn}
' fnn o-> nnn2_
' {body_fn}
@enduml