@startuml rete
garg2e2_ -> gig_mall_ 
farg2e2_ -> gig_mall_
echo_deb_ -> gig_mall_
gig_mall_ -> gig_mall_:is_num
gig_mall_ -> gig_mall_:exit_err_gig_mall_
gig_mall_ -> gig_mall_:exit_reg_gig_mall_
gig_mall_ -> gig_mall_:unset_autoargs_gig_mall_
' {wrap_fn}
' fnn o-> gig_mall_
' {body_fn}
@enduml