#!/bin/bash

#. "$HOME/.bashrc"

filename=repo/.git/hooks/pre-commit

bsh_() {
    . $HOME/.bashrc
}

bsh_ 1>/dev/null

list=${PLT_PATH}/.d/.tst/local.list

if up_err_ tst ${list} 1>/dev/null; then
    echo -e "${BLUE}---INIT0 patch in ${list} with EXIT 0---${NORMAL}"  #sistem info mesage
    exit 0
else
    echo -e "${RED}---INIT0 patch in ${list} with EXIT 1---${NORMAL}" >&2 #sistem info mesage
    exit 1
fi



#----------
#----------------------------
#------------------------------------------------------
unset filename

# exit 0
