${FONSH_PATH}/actio
${PLT_PATH}/actio
${PATH_COMMUNIS}/Deploy_store/.qa
${PATH_TST_DIR}
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_lib
${PATH_COMMUNIS}/Deploy_store/.qa/lib/_stl_tmp_4
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_lib/_tst
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_lib/_debug
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_man
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_man/nbase/_Head_sis_libs_v.cplus
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_man/nbase/_Head_sis_libs_posix
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_man/nbase/_Client_Server
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_man/nbase/_Lib_into_Lib
#${PATH_MAIN_REPO_FN_DIR}/dir_c_/_c_/_exec
${PATH_COMMUNIS}/Deploy_store/.qa/_Bash_Projects/_UpErrLevels/v3_up_2_level