@startuml rete
garg2e2_ -> cr_sh2_ 
farg2e2_ -> cr_sh2_
echo_deb_ -> cr_sh2_
cr_sh2_ -> cr_sh2_:is_num
cr_sh2_ -> cr_sh2_:exit_err_cr_sh2_
cr_sh2_ -> cr_sh2_:exit_reg_cr_sh2_
cr_sh2_ -> cr_sh2_:unset_autoargs_cr_sh2_
' {wrap_fn}
' fnn o-> cr_sh2_
' {body_fn}
@enduml