@startuml rete
garg2e2_ -> el_f_prp_ 
farg2e2_ -> el_f_prp_
echo_deb_ -> el_f_prp_
el_f_prp_ -> el_f_prp_:is_num
el_f_prp_ -> el_f_prp_:exit_err_el_f_prp_
el_f_prp_ -> el_f_prp_:exit_reg_el_f_prp_
el_f_prp_ -> el_f_prp_:unset_autoargs_el_f_prp_
' {wrap_fn}
' fnn o-> el_f_prp_
' {body_fn}
@enduml