#!/bin/sh
#
# License?
#

#
# UUID раздела
#
#PART_UUID="`/sbin/blkid -o value -s UUID /dev/${1}`"

#
# LABEL раздела
#
PART_LABEL=$(/sbin/blkid -p -o value -s LABEL /dev/${1} | /bin/sed 's/ /_/g')

#
# FS раздела
#
PART_FS=$(/sbin/blkid -o value -s TYPE /dev/${1})

#
# Проверить подключается устройство или отключается?
#
if [ "$2" = "plugdev" ]
then /bin/mkdir /media/${1}.${PART_LABEL}

#
# Определить, не смонтирован ли уже раздел?
#
# if [grep -e ${1} -e mount]
# then printf Всё смонтировано, я в отбой. && exit 0

case ${PART_FS} in

vfat)
/bin/echo /dev/${1} /media/${1}.${PART_LABEL} vfat shortname=lower,iocharset=utf8,noatime,users,dmask=000,fmask=111 0 0 >> /etc/fstab
/bin/mount /dev/${1}
;;

ntfs)
/bin/echo /dev/${1} /media/${1}.${PART_LABEL} ntfs-3g relatime,users,dmask=000,fmask=111 0 0 >> /etc/fstab
/bin/mount /dev/${1}
;;

*)
/bin/echo /dev/${1} /media/${1}.${PART_LABEL} auto users 0 0 >> /etc/fstab
/bin/mount /dev/${1}
;;

esac
else
/bin/umount -l /dev/${1}
/bin/rmdir --ignore-fail-on-non-empty "$(/usr/bin/awk "/${1}/ { print \$2 }" < /etc/fstab)"
/bin/sed "/\/dev\/${1}/d" -i /etc/fstab
fi

exit 0