@startuml rete
garg2e2_ -> bd_communis_v2_ 
farg2e2_ -> bd_communis_v2_
echo_deb_ -> bd_communis_v2_
bd_communis_v2_ -> bd_communis_v2_:is_num
bd_communis_v2_ -> bd_communis_v2_:exit_err_bd_communis_v2_
bd_communis_v2_ -> bd_communis_v2_:exit_reg_bd_communis_v2_
bd_communis_v2_ -> bd_communis_v2_:unset_autoargs_bd_communis_v2_
' {wrap_fn}
' fnn o-> bd_communis_v2_
' {body_fn}
@enduml