@startuml rete
garg2e2_ -> dr2e_v2_ 
farg2e2_ -> dr2e_v2_
echo_deb_ -> dr2e_v2_
dr2e_v2_ -> dr2e_v2_:is_num
dr2e_v2_ -> dr2e_v2_:exit_err_dr2e_v2_
dr2e_v2_ -> dr2e_v2_:exit_reg_dr2e_v2_
dr2e_v2_ -> dr2e_v2_:unset_autoargs_dr2e_v2_
' {wrap_fn}
' fnn o-> dr2e_v2_
' {body_fn}
@enduml