@startuml rete
garg2e2_ -> bcp_conf_ 
farg2e2_ -> bcp_conf_
echo_deb_ -> bcp_conf_
bcp_conf_ -> bcp_conf_:is_num
bcp_conf_ -> bcp_conf_:exit_err_bcp_conf_
bcp_conf_ -> bcp_conf_:exit_reg_bcp_conf_
bcp_conf_ -> bcp_conf_:unset_autoargs_bcp_conf_
' {wrap_fn}
' fnn o-> bcp_conf_
' {body_fn}
@enduml