@startuml rete
garg2e2_ -> mm_execf_ 
farg2e2_ -> mm_execf_
echo_deb_ -> mm_execf_
mm_execf_ -> mm_execf_:is_num
mm_execf_ -> mm_execf_:exit_err_mm_execf_
mm_execf_ -> mm_execf_:exit_reg_mm_execf_
mm_execf_ -> mm_execf_:unset_autoargs_mm_execf_
' {wrap_fn}
' fnn o-> mm_execf_
' {body_fn}
@enduml